<a href="https://colab.research.google.com/github/Nimira43/Business-Data-Analytics-Intelligence/blob/main/Basic_Statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Basic Statistics

In [4]:
#change directory
%cd /content/drive/MyDrive/Colab Notebooks/Business Data Analytics/01-Basic-Statistics

/content/drive/MyDrive/Colab Notebooks/Business Data Analytics/01-Basic-Statistics

In [5]:
#libraries
import pandas as pd
import seaborn as sns

In [6]:
#dataset
df = pd.read_csv('Baseball.csv')
df.head()

,Team,League,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG
0,ARI,NL,2012,734,688,81,0.328,0.418,0.259,0,NaN,NaN,162,0.317,0.415
1,ATL,NL,2012,700,600,94,0.320,0.389,0.247,1,4.0,5.0,162,0.306,0.378
2,BAL,AL,2012,712,705,93,0.311,0.417,0.247,1,5.0,4.0,162,0.315,0.403
3,BOS,AL,2012,734,806,69,0.315,0.415,0.260,0,NaN,NaN,162,0.331,0.428
4,CHC,NL,2012,613,759,61,0.302,0.378,0.240,0,NaN,NaN,162,0.335,0.424

##Mean

In [7]:
#Mean of runs scored - rs
df.RS.mean()

715.0819805194806

In [9]:
#Arizona data
df.loc[df.Team == 'ARI']

,Team,League,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG
0,ARI,NL,2012,734,688,81,0.328,0.418,0.259,0,NaN,NaN,162,0.317,0.415
30,ARI,NL,2011,731,662,94,0.322,0.413,0.250,1,5.0,4.0,162,0.316,0.409
60,ARI,NL,2010,713,836,65,0.325,0.416,0.250,0,NaN,NaN,162,0.340,0.448
90,ARI,NL,2009,720,782,70,0.324,0.418,0.253,0,NaN,NaN,162,0.330,0.419
120,ARI,NL,2008,720,706,82,0.327,0.415,0.251,0,NaN,NaN,162,0.318,0.398
150,ARI,NL,2007,712,732,90,0.321,0.413,0.250,1,3.0,3.0,162,0.334,0.420
180,ARI,NL,2006,773,788,76,0.331,0.424,0.267,0,NaN,NaN,162,0.335,0.431
210,ARI,NL,2005,696,856,77,0.332,0.421,0.256,0,NaN,NaN,162,0.345,0.455
241,ARI,NL,2004,615,899,51,0.310,0.393,0.253,0,NaN,NaN,162,0.350,0.439
271,ARI,NL,2003,717,685,84,0.330,0.417,0.263,0,NaN,NaN,162,0.322,0.388
301,ARI,NL,2002,819,674,98,0.346,0.423,0.267,1,4.0,4.0,162,0.305,0.397
331,ARI,NL,2001,818,677,92,0.341,0.442,0.267,1,5.0,1.0,162,0.311,0.404
361,ARI,NL,2000,792,754,85,0.333,0.429,0.265,0,NaN,NaN,162,0.326,0.424
391,ARI,NL,1999,908,676,100,0.347,0.459,0.277,1,2.0,4.0,162,0.320,0.402
421,ARI,NL,1998,665,812,65,0.314,0.393,0.246,0,NaN,NaN,162,NaN,NaN

In [10]:
#Mean of runs scored - rs - Arizona
df.loc[df.Team == 'ARI'].RS.mean()

742.2

In [ ]:
#Mean of runs scored - rs - Arizona - since 2005

In [ ]:
#Mean of runs scored - rs - Chicago

In [ ]:
#Mean of runs scored - rs - Chicago - since 2005