<a href="https://colab.research.google.com/github/Nimira43/Business-Data-Analytics-Intelligence/blob/main/Basic%20Statistics/Basic_Statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Libraries, Directory & Data

In [1]:
#change directory
%cd /content/drive/MyDrive/COMPUTER SCIENCES/ZTM/BUSINESS DATA ANALYTICS/Statistics and Descriptive Analytics/Basic Statistics

/content/drive/MyDrive/COMPUTER SCIENCES/ZTM/BUSINESS DATA ANALYTICS/Statistics and Descriptive Analytics/Basic Statistics

In [2]:
#Libraries
import pandas as pd
import seaborn as sns

In [3]:
#Load the dataset
df = pd.read_csv("Baseball.csv")
df.head()

,Team,League,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG
0,ARI,NL,2012,734,688,81,0.328,0.418,0.259,0,NaN,NaN,162,0.317,0.415
1,ATL,NL,2012,700,600,94,0.320,0.389,0.247,1,4.0,5.0,162,0.306,0.378
2,BAL,AL,2012,712,705,93,0.311,0.417,0.247,1,5.0,4.0,162,0.315,0.403
3,BOS,AL,2012,734,806,69,0.315,0.415,0.260,0,NaN,NaN,162,0.331,0.428
4,CHC,NL,2012,613,759,61,0.302,0.378,0.240,0,NaN,NaN,162,0.335,0.424

Test - send to Github

##Mean

In [4]:
#Mean of runs scored (RS)
df.RS.mean()

715.0819805194806

In [5]:
#Runs scored (RS) by BOS - Boston
df.loc[df.Team == "BOS"]

,Team,League,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG
3,BOS,AL,2012,734,806,69,0.315,0.415,0.260,0,NaN,NaN,162,0.331,0.428
33,BOS,AL,2011,875,737,90,0.349,0.461,0.280,0,NaN,NaN,162,0.322,0.392
63,BOS,AL,2010,818,744,89,0.339,0.451,0.268,0,NaN,NaN,162,0.327,0.399
93,BOS,AL,2009,872,736,95,0.352,0.454,0.270,1,3.0,4.0,162,0.335,0.422
123,BOS,AL,2008,845,694,95,0.358,0.447,0.280,1,3.0,3.0,162,0.323,0.390
153,BOS,AL,2007,867,657,96,0.362,0.444,0.279,1,1.0,1.0,162,0.314,0.392
183,BOS,AL,2006,820,825,86,0.351,0.435,0.269,0,NaN,NaN,162,0.343,0.447
213,BOS,AL,2005,910,805,95,0.357,0.454,0.281,1,3.0,4.0,162,0.335,0.441
244,BOS,AL,2004,949,768,98,0.360,0.472,0.282,1,3.0,1.0,162,0.318,0.408
274,BOS,AL,2003,961,809,95,0.360,0.491,0.289,1,4.0,3.0,162,0.327,0.415
304,BOS,AL,2002,859,665,93,0.345,0.444,0.277,0,NaN,NaN,162,0.308,0.385
334,BOS,AL,2001,772,745,82,0.334,0.439,0.266,0,NaN,NaN,161,0.329,0.393
364,BOS,AL,2000,792,745,85,0.341,0.423,0.267,0,NaN,NaN,162,0.322,0.411
394,BOS,AL,1999,836,718,94,0.350,0.448,0.278,1,6.0,3.0,162,0.315,0.398
424,BOS,AL,1998,876,729,92,0.348,0.463,0.280,1,5.0,4.0,162,NaN,NaN
453,BOS,AL,1997,851,857,78,0.352,0.463,0.291,0,NaN,NaN,162,NaN,NaN
480,BOS,AL,1996,928,921,85,0.359,0.457,0.283,0,NaN,NaN,162,NaN,NaN
508,BOS,AL,1993,686,698,80,0.330,0.395,0.264,0,NaN,NaN,162,NaN,NaN
536,BOS,AL,1992,599,669,73,0.321,0.347,0.246,0,NaN,NaN,162,NaN,NaN
562,BOS,AL,1991,731,712,84,0.340,0.401,0.269,0,NaN,NaN,162,NaN,NaN
588,BOS,AL,1990,699,664,88,0.344,0.395,0.272,1,4.0,3.0,162,NaN,NaN
614,BOS,AL,1989,774,735,83,0.351,0.403,0.277,0,NaN,NaN,162,NaN,NaN
640,BOS,AL,1988,813,689,89,0.357,0.420,0.283,1,4.0,3.0,162,NaN,NaN
666,BOS,AL,1987,842,825,78,0.352,0.430,0.278,0,NaN,NaN,162,NaN,NaN
692,BOS,AL,1986,794,696,95,0.346,0.415,0.271,1,3.0,2.0,161,NaN,NaN
718,BOS,AL,1985,800,720,81,0.347,0.429,0.282,0,NaN,NaN,163,NaN,NaN
744,BOS,AL,1984,810,764,86,0.341,0.441,0.283,0,NaN,NaN,162,NaN,NaN
770,BOS,AL,1983,724,775,78,0.335,0.409,0.270,0,NaN,NaN,162,NaN,NaN
796,BOS,AL,1982,753,713,89,0.340,0.407,0.274,0,NaN,NaN,162,NaN,NaN
822,BOS,AL,1980,757,767,83,0.340,0.436,0.283,0,NaN,NaN,160,NaN,NaN
848,BOS,AL,1979,841,711,91,0.344,0.456,0.283,0,NaN,NaN,160,NaN,NaN
874,BOS,AL,1978,796,657,99,0.336,0.424,0.267,0,NaN,NaN,163,NaN,NaN
900,BOS,AL,1977,859,712,97,0.345,0.465,0.281,0,NaN,NaN,161,NaN,NaN
926,BOS,AL,1976,716,660,83,0.324,0.402,0.263,0,NaN,NaN,162,NaN,NaN
950,BOS,AL,1975,796,709,95,0.344,0.417,0.275,1,3.0,2.0,160,NaN,NaN
974,BOS,AL,1974,696,661,84,0.333,0.377,0.264,0,NaN,NaN,162,NaN,NaN
998,BOS,AL,1973,738,647,89,0.338,0.401,0.267,0,NaN,NaN,162,NaN,NaN
1022,BOS,AL,1971,691,667,85,0.322,0.397,0.252,0,NaN,NaN,162,NaN,NaN
1046,BOS,AL,1970,786,722,87,0.335,0.428,0.262,0,NaN,NaN,162,NaN,NaN
1070,BOS,AL,1969,743,736,87,0.333,0.415,0.251,0,NaN,NaN,162,NaN,NaN
1094,BOS,AL,1968,614,611,86,0.313,0.352,0.236,0,NaN,NaN,162,NaN,NaN
1114,BOS,AL,1967,722,614,92,0.321,0.395,0.255,1,2.0,2.0,162,NaN,NaN
1134,BOS,AL,1966,655,731,72,0.310,0.376,0.240,0,NaN,NaN,162,NaN,NaN
1153,BOS,AL,1965,669,791,62,0.327,0.400,0.251,0,NaN,NaN,162,NaN,NaN
1173,BOS,AL,1964,688,793,72,0.322,0.416,0.258,0,NaN,NaN,162,NaN,NaN
1193,BOS,AL,1963,666,704,76,0.312,0.400,0.252,0,NaN,NaN,161,NaN,NaN
1213,BOS,AL,1962,707,756,76,0.324,0.403,0.258,0,NaN,NaN,160,NaN,NaN

In [6]:
#Mean Runs scored (RS) by BOS - Boston
df.loc[df.Team == "BOS"].RS.mean()

781.4893617021277

In [7]:
#Mean Runs scored (RS) by AZI - Arizona
df.loc[df.Team == "ARI"].RS.mean()

742.2

In [9]:
#Runs scored (RS) by BOS since 2002
df.loc[(df.Team == "BOS") & (df.Year > 2002) ]

,Team,League,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG
3,BOS,AL,2012,734,806,69,0.315,0.415,0.260,0,NaN,NaN,162,0.331,0.428
33,BOS,AL,2011,875,737,90,0.349,0.461,0.280,0,NaN,NaN,162,0.322,0.392
63,BOS,AL,2010,818,744,89,0.339,0.451,0.268,0,NaN,NaN,162,0.327,0.399
93,BOS,AL,2009,872,736,95,0.352,0.454,0.270,1,3.0,4.0,162,0.335,0.422
123,BOS,AL,2008,845,694,95,0.358,0.447,0.280,1,3.0,3.0,162,0.323,0.390
153,BOS,AL,2007,867,657,96,0.362,0.444,0.279,1,1.0,1.0,162,0.314,0.392
183,BOS,AL,2006,820,825,86,0.351,0.435,0.269,0,NaN,NaN,162,0.343,0.447
213,BOS,AL,2005,910,805,95,0.357,0.454,0.281,1,3.0,4.0,162,0.335,0.441
244,BOS,AL,2004,949,768,98,0.360,0.472,0.282,1,3.0,1.0,162,0.318,0.408
274,BOS,AL,2003,961,809,95,0.360,0.491,0.289,1,4.0,3.0,162,0.327,0.415

In [10]:
#Mean number of Runs scored (RS) by BOS since 2002
df.loc[(df.Team == "BOS") & (df.Year > 2002) ].RS.mean()

865.1

In [13]:
#Mean of Runs Allowed (RA) for CHC - Chicargo until 2007
df.loc[(df.Team == "CHC") & (df.Year < 2007)].RA.mean()

728.170731707317